(setq smiley-data-directory "~/.emacs.d/icons/smileys")
(setq smiley-regexp-alist
      (mapcar
       (lambda (regexp-smiley)
         `(,(concat "\\(?: \\|\s+\\|^\\)\\(" (car regexp-smiley) "\\)\\(?: \\|\s+\\|$\\)")
           1 ,(cdr regexp-smiley)))
       '((":-?)" . "smile")
         (";-?)" . "blink")
         ("8-)" . "crazy")
         ("x-?D" . "lol")
         ("lol" . "lol")
         (":-?|" . "indifferent")
         (":-?(" . "sad")
         (":-?D" . "grin")
         ("\\*g\\*" . "grin")
         (":-?P" . "p")
         (";-?(" . "cry")
         (">:-?)" . "evil")
         ("(L)" . "love")
         ("<3" . "love")
         ("(K)" . "kiss")
         ("☺" . "smile"))))

(provide 'jd-smiley)
